### ISSUE TITLE
why hath Alex so few commits?

### ISSUE THREAD

**Issue by tofr** [siuryan/Simplicity#1]
?
?
?

**Comment by erichzg** [comment]
Sorry Mr. Brown. I was working on the algorithm for most of this time, but I had to go through a few iterations of the implementation not through the repo. Now that it's working correctly (hopefully), my commitment (?) should increase.

**Comment by erichzg** [comment]
It also turns out that my home computer wasn't connected to my stuy.edu email, so it wasn't committing with this account. That problem is now fixed.

**Comment by tofr** [comment]
Insight appreciated. Glad to hear this has been rectified.

​

Topher Brown Mykolyk
CS - Stuyvesant HS
+
